# Generated by Django 4.1.7 on 2023-09-21 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(max_length=32, verbose_name="部门名称"),
                ),
                ("employees_num", models.IntegerField(verbose_name="员工人数")),
            ],
        ),
        migrations.CreateModel(
            name="Parts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=64, verbose_name="零件编号")),
                ("name", models.CharField(max_length=32, verbose_name="零件名称")),
                ("unit", models.CharField(max_length=32, verbose_name="计量单位")),
                ("amount", models.IntegerField(verbose_name="库存量")),
                ("price", models.FloatField(verbose_name="单价")),
                ("store", models.CharField(max_length=64, verbose_name="仓库存储位置")),
                ("description", models.CharField(max_length=128, verbose_name="附加描述")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("password", models.CharField(max_length=63, verbose_name="密码")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("create_time", models.DateField(verbose_name="入职时间")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid", models.CharField(max_length=64, verbose_name="订单号")),
                ("sale_num", models.IntegerField(default=0, verbose_name="销售数量")),
                ("profit", models.FloatField(verbose_name="销售利润")),
                (
                    "customer",
                    models.CharField(
                        choices=[("公司", "公司"), ("小型企业", "小型企业"), ("消费者", "消费者")],
                        default="小型企业",
                        max_length=64,
                        verbose_name="采购方",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.parts",
                        verbose_name="商品名称",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AjaxTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "紧急"), (2, "重要"), (3, "临时")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("detail", models.TextField(verbose_name="详细信息")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.admin",
                        verbose_name="负责人",
                    ),
                ),
            ],
        ),
    ]
